#!/bin/bash
# ElevatedIQ News Feed Engine - Environment Setup Script
# Run this script to set up the development environment

set -e

echo "🚀 ElevatedIQ News Feed Engine - Environment Setup"
echo "=================================================="

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Check prerequisites
check_prereqs() {
    echo -e "\n${YELLOW}Checking prerequisites...${NC}"

    # Check Python
    if command -v python3 &> /dev/null; then
        PYTHON_VERSION=$(python3 --version 2>&1 | awk '{print $2}')
        echo -e "${GREEN}✓ Python ${PYTHON_VERSION}${NC}"
    else
        echo -e "${RED}✗ Python 3 not found${NC}"
        exit 1
    fi

    # Check Go
    if command -v go &> /dev/null; then
        GO_VERSION=$(go version | awk '{print $3}')
        echo -e "${GREEN}✓ Go ${GO_VERSION}${NC}"
    else
        echo -e "${YELLOW}⚠ Go not found (optional for Python-only dev)${NC}"
    fi

    # Check Docker
    if command -v docker &> /dev/null; then
        DOCKER_VERSION=$(docker --version | awk '{print $3}' | tr -d ',')
        echo -e "${GREEN}✓ Docker ${DOCKER_VERSION}${NC}"
    else
        echo -e "${RED}✗ Docker not found${NC}"
        exit 1
    fi

    # Check docker-compose
    if command -v docker-compose &> /dev/null; then
        DC_VERSION=$(docker-compose --version | awk '{print $4}' | tr -d ',')
        echo -e "${GREEN}✓ Docker Compose ${DC_VERSION}${NC}"
    else
        echo -e "${YELLOW}⚠ docker-compose not found, trying docker compose...${NC}"
    fi
}

# Create virtual environment
setup_python_env() {
    echo -e "\n${YELLOW}Setting up Python environment...${NC}"

    cd processor

    # Create venv if it doesn't exist
    if [ ! -d "venv" ]; then
        python3 -m venv venv
        echo -e "${GREEN}✓ Created virtual environment${NC}"
    fi

    # Activate and install dependencies
    source venv/bin/activate
    pip install --upgrade pip setuptools wheel
    pip install -r requirements.txt

    echo -e "${GREEN}✓ Installed Python dependencies${NC}"
    cd ..
}

# Setup environment file
setup_env_file() {
    echo -e "\n${YELLOW}Setting up environment file...${NC}"

    if [ ! -f ".env" ]; then
        if [ -f "config/.env.example" ]; then
            cp config/.env.example .env
            echo -e "${GREEN}✓ Created .env from template${NC}"
            echo -e "${YELLOW}⚠ Please edit .env with your API keys${NC}"
        else
            echo -e "${YELLOW}⚠ No .env.example found, creating basic .env${NC}"
            cat > .env << 'EOF'
# ElevatedIQ News Feed Engine Environment Variables
# Generated by setup-env.sh

# AI Services
ANTHROPIC_API_KEY=your_claude_api_key
ELEVENLABS_API_KEY=your_elevenlabs_key
DID_API_KEY=your_did_api_key
OPENAI_API_KEY=your_openai_key

# Media Manager
MEDIA_MANAGER_URL=https://media.elevatediq.com
MEDIA_MANAGER_API_KEY=your_media_manager_key

# Trend Sources (optional for development)
GOOGLE_TRENDS_API_KEY=
TWITTER_BEARER_TOKEN=
REDDIT_CLIENT_ID=
REDDIT_CLIENT_SECRET=
YOUTUBE_API_KEY=
NEWS_API_KEY=
TIKTOK_API_KEY=

# Infrastructure
KAFKA_BOOTSTRAP_SERVERS=127.0.0.1:9092
REDIS_URL=redis://127.0.0.1:6379
POSTGRES_URL=postgresql://postgres:postgres@127.0.0.1:5432/news_feed
MONGODB_URI=mongodb://127.0.0.1:27017/news_feed

# Encryption
TOKEN_ENCRYPTION_KEY=generate_with_python_-c_"from_cryptography.fernet_import_Fernet;_print(Fernet.generate_key().decode())"
EOF
        fi
    else
        echo -e "${GREEN}✓ .env already exists${NC}"
    fi
}

# Start infrastructure services
start_infrastructure() {
    echo -e "\n${YELLOW}Starting infrastructure services...${NC}"

    # Check if docker-compose file exists
    if [ -f "docker-compose.news-feed.yml" ]; then
        docker-compose -f docker-compose.news-feed.yml up -d \
            elevatediq-postgres elevatediq-redis elevatediq-mongodb elevatediq-kafka
        echo -e "${GREEN}✓ Started database and message queue services${NC}"
    else
        echo -e "${YELLOW}⚠ docker-compose.news-feed.yml not found${NC}"
        echo -e "${YELLOW}  You'll need to start infrastructure manually${NC}"
    fi
}

# Run database migrations
run_migrations() {
    echo -e "\n${YELLOW}Running database migrations...${NC}"

    if [ -d "migrations" ]; then
        # Wait for PostgreSQL to be ready
        sleep 5

        for migration in migrations/*.sql; do
            if [ -f "$migration" ]; then
                PGPASSWORD=postgres psql -h 127.0.0.1 -U postgres -d news_feed -f "$migration" 2>/dev/null || true
                echo -e "${GREEN}✓ Applied $(basename $migration)${NC}"
            fi
        done
    else
        echo -e "${YELLOW}⚠ No migrations directory found${NC}"
    fi
}

# Validate installation
validate_install() {
    echo -e "\n${YELLOW}Validating installation...${NC}"

    cd processor
    source venv/bin/activate

    # Try importing modules
    python3 -c "
import sys
try:
    from processor.config import Settings
    print('✓ Config module')
except ImportError as e:
    print(f'⚠ Config module: {e}')

try:
    from processor.predictive_engine import ContentPredictor
    print('✓ Predictive engine')
except ImportError as e:
    print(f'⚠ Predictive engine: {e}')

try:
    from processor.ai_agents import AgentOrchestrator
    print('✓ AI agents')
except ImportError as e:
    print(f'⚠ AI agents: {e}')

try:
    from processor.trend_sources import TrendAggregator
    print('✓ Trend sources')
except ImportError as e:
    print(f'⚠ Trend sources: {e}')

try:
    from processor.analytics_pipeline import AnalyticsPipeline
    print('✓ Analytics pipeline')
except ImportError as e:
    print(f'⚠ Analytics pipeline: {e}')

try:
    from processor.oauth_manager import OAuthManager
    print('✓ OAuth manager')
except ImportError as e:
    print(f'⚠ OAuth manager: {e}')
" 2>&1

    cd ..
}

# Main execution
main() {
    # Navigate to service directory
    SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    SERVICE_DIR="$(dirname "$SCRIPT_DIR")"
    cd "$SERVICE_DIR"

    check_prereqs
    setup_python_env
    setup_env_file

    # Optional: start infrastructure
    read -p "Start infrastructure services (Docker)? [y/N] " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        start_infrastructure
        run_migrations
    fi

    validate_install

    echo -e "\n${GREEN}=================================================="
    echo "✅ Setup complete!"
    echo "=================================================="
    echo -e "${NC}"
    echo "Next steps:"
    echo "1. Edit .env with your API keys"
    echo "2. Activate Python venv: source processor/venv/bin/activate"
    echo "3. Start the service: go run ./cmd/news-feed"
    echo ""
}

main "$@"
