#!/bin/bash
# ELEVATEDIQ GLOBAL ENVIRONMENT CONFIGURATION
# Sourced by all deployment scripts for consistency

# Domain & Branding
export ELEVATEDIQ_DOMAIN="elevatediq.ai"
export ELEVATEDIQ_BRAND_NAME="ElevatedIQ"
export ELEVATEDIQ_LOGO_URL="https://elevatediq.ai/logo.png"

# Global Logging
export ELEVATEDIQ_LOG_LEVEL="${ELEVATEDIQ_LOG_LEVEL:-info}"
export ELEVATEDIQ_LOG_FORMAT="${ELEVATEDIQ_LOG_FORMAT:-json}"

# Monitoring
export ELEVATEDIQ_METRICS_ENABLED="${ELEVATEDIQ_METRICS_ENABLED:-true}"
export ELEVATEDIQ_TRACING_ENABLED="${ELEVATEDIQ_TRACING_ENABLED:-true}"
export ELEVATEDIQ_PROFILING_ENABLED="${ELEVATEDIQ_PROFILING_ENABLED:-false}"

# Security
export ELEVATEDIQ_TLS_ENABLED="${ELEVATEDIQ_TLS_ENABLED:-true}"
export ELEVATEDIQ_CORS_ENABLED="${ELEVATEDIQ_CORS_ENABLED:-true}"
export ELEVATEDIQ_RATE_LIMIT_ENABLED="${ELEVATEDIQ_RATE_LIMIT_ENABLED:-true}"

# Machine Learning
export ELEVATEDIQ_ML_MODEL_VERSION="${ELEVATEDIQ_ML_MODEL_VERSION:-1.0.0}"
export ELEVATEDIQ_ML_BATCH_SIZE="${ELEVATEDIQ_ML_BATCH_SIZE:-32}"

# Storage
export ELEVATEDIQ_STORAGE_TYPE="${ELEVATEDIQ_STORAGE_TYPE:-s3}"

# All URLs use domain
export ELEVATEDIQ_API_BASE_URL="https://api.${ELEVATEDIQ_DOMAIN}"
export ELEVATEDIQ_PORTAL_URL="https://portal.${ELEVATEDIQ_DOMAIN}"
export ELEVATEDIQ_ADMIN_URL="https://admin.${ELEVATEDIQ_DOMAIN}"

echo "✓ ElevatedIQ global configuration loaded"
